scmi-msg: clk: fix conflict types
core/drivers/scmi-msg/clock.c:358:13: error: conflicting types for 'message_id_is_supported'
 static bool message_id_is_supported(size_t message_id)
             ^~~~~~~~~~~~~~~~~~~~~~~
core/drivers/scmi-msg/clock.c:16:13: note: previous declaration of 'message_id_is_supported' was here
 static bool message_id_is_supported(unsigned int message_id);

Align with the message parameter which is uint32_t type.

Signed-off-by: Lionel Debieve <lionel.debieve@st.com>
Change-Id: Ib9d2285933f9f9dcdd3f7bab65c5324b5c94141a
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/190694
Reviewed-by: CITOOLS <MDG-smet-aci-reviews@list.st.com>